
> bp-site@0.1.0 start
> concurrently "node server.js" "next start"

[1] - ready started server on 0.0.0.0:3000, url: http://localhost:3000
[0] node:events:491
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE: address already in use :::5000
[0]     at Server.setupListenHandle [as _listen2] (node:net:1463:16)
[0]     at listenInCluster (node:net:1511:12)
[0]     at Server.listen (node:net:1599:7)
[0]     at Function.listen (/vagrant/ansible/nextjs_react/bp-site/node_modules/express/lib/application.js:635:24)
[0]     at Object.<anonymous> (/vagrant/ansible/nextjs_react/bp-site/server.js:51:5)
[0]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[0]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[0]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (node:net:1490:8)
[0]     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -98,
[0]   syscall: 'listen',
[0]   address: '::',
[0]   port: 5000
[0] }
[0] node server.js exited with code 1
[1] Error: Could not find a production build in the '/vagrant/ansible/nextjs_react/bp-site/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
[1]     at NextNodeServer.getBuildId (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next-server.js:348:23)
[1]     at new Server (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/base-server.js:153:29)
[1]     at new NextNodeServer (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next-server.js:175:9)
[1]     at NextServer.createServer (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next.js:179:24)
[1]     at async /vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next.js:200:31
[1]     at async NextServer.prepare (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next.js:161:24)
[1]     at async Server.<anonymous> (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/lib/render-server.js:136:17) {
[1]   type: 'Error'
[1] }
[1] next start exited with code 1
npm notice 
npm notice New major version of npm available! 8.19.4 -> 9.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
npm notice Run `npm install -g npm@9.8.1` to update!
npm notice 

> bp-site@0.1.0 start
> concurrently "node server.js" "next start"

[1] - ready started server on 0.0.0.0:3000, url: http://localhost:3000
[0] node:events:491
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE: address already in use :::5000
[0]     at Server.setupListenHandle [as _listen2] (node:net:1463:16)
[0]     at listenInCluster (node:net:1511:12)
[0]     at Server.listen (node:net:1599:7)
[0]     at Function.listen (/vagrant/ansible/nextjs_react/bp-site/node_modules/express/lib/application.js:635:24)
[0]     at Object.<anonymous> (/vagrant/ansible/nextjs_react/bp-site/server.js:51:5)
[0]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[0]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[0]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (node:net:1490:8)
[0]     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -98,
[0]   syscall: 'listen',
[0]   address: '::',
[0]   port: 5000
[0] }
[0] node server.js exited with code 1
[1] Error: Could not find a production build in the '/vagrant/ansible/nextjs_react/bp-site/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
[1]     at NextNodeServer.getBuildId (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next-server.js:348:23)
[1]     at new Server (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/base-server.js:153:29)
[1]     at new NextNodeServer (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next-server.js:175:9)
[1]     at NextServer.createServer (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next.js:179:24)
[1]     at async /vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next.js:200:31
[1]     at async NextServer.prepare (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next.js:161:24)
[1]     at async Server.<anonymous> (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/lib/render-server.js:136:17) {
[1]   type: 'Error'
[1] }
[1] next start exited with code 1

> bp-site@0.1.0 start
> concurrently "node server.js" "next start"

[1] - ready started server on 0.0.0.0:3000, url: http://localhost:3000
[0] node:events:491
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE: address already in use :::5000
[0]     at Server.setupListenHandle [as _listen2] (node:net:1463:16)
[0]     at listenInCluster (node:net:1511:12)
[0]     at Server.listen (node:net:1599:7)
[0]     at Function.listen (/vagrant/ansible/nextjs_react/bp-site/node_modules/express/lib/application.js:635:24)
[0]     at Object.<anonymous> (/vagrant/ansible/nextjs_react/bp-site/server.js:51:5)
[0]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[0]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[0]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (node:net:1490:8)
[0]     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -98,
[0]   syscall: 'listen',
[0]   address: '::',
[0]   port: 5000
[0] }
[0] node server.js exited with code 1
[1] Error: Could not find a production build in the '/vagrant/ansible/nextjs_react/bp-site/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
[1]     at NextNodeServer.getBuildId (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next-server.js:348:23)
[1]     at new Server (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/base-server.js:153:29)
[1]     at new NextNodeServer (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next-server.js:175:9)
[1]     at NextServer.createServer (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next.js:179:24)
[1]     at async /vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next.js:200:31
[1]     at async NextServer.prepare (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/next.js:161:24)
[1]     at async Server.<anonymous> (/vagrant/ansible/nextjs_react/bp-site/node_modules/next/dist/server/lib/render-server.js:136:17) {
[1]   type: 'Error'
[1] }
[1] next start exited with code 1

> bp-site@0.1.0 start
> concurrently "node server.js" "next start"

[1] - ready started server on 0.0.0.0:3000, url: http://localhost:3000
[0] node:events:491
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE: address already in use :::5000
[0]     at Server.setupListenHandle [as _listen2] (node:net:1463:16)
[0]     at listenInCluster (node:net:1511:12)
[0]     at Server.listen (node:net:1599:7)
[0]     at Function.listen (/vagrant/ansible/nextjs_react/bp-site/node_modules/express/lib/application.js:635:24)
[0]     at Object.<anonymous> (/vagrant/ansible/nextjs_react/bp-site/server.js:51:5)
[0]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[0]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[0]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (node:net:1490:8)
[0]     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -98,
[0]   syscall: 'listen',
[0]   address: '::',
[0]   port: 5000
[0] }
[0] node server.js exited with code 1
